include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

image: docker:20.10.5

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.5-dind

stages:
  - check
  - test
  - deploy


.secret-analyzer:
  stage: check


build and test:
  image: node:latest
  stage: test
  script:
    - npm install npm@7.5.6 -g
    - npm install
    - npm test

deploy-tagged-docker-image:
  stage: deploy
  script:
    - docker build --target prod -t iqbberlin/testcenter-broadcasting-service:$CI_COMMIT_TAG -f docker/Dockerfile .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push iqbberlin/testcenter-broadcasting-service:$CI_COMMIT_TAG
  rules:
    - if: "$CI_COMMIT_TAG"
