version: '3.7'

services:

  testcenter-broadcasting-service-dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: ${TARGET:-dev}
    container_name: testcenter-broadcasting-service-${TARGET:-dev}
    volumes:
      - ./broadcasting-service/nest-cli.docker.json:/app/nest-cli.json
      - ./broadcasting-service/package.json:/app/package.json
      - ./broadcasting-service/src:/app/src
      - ./broadcasting-service/tsconfig.build.json:/app/tsconfig.build.json
      - ./broadcasting-service/tsconfig.json:/app/tsconfig.json
      - testcenter_broadcasting_service_dev_node_modules:/app/node_modules
    ports:
      - '3000:3000'

volumes:
  testcenter_broadcasting_service_dev_node_modules:
